// Every car in the showroom. Specs come from manufacturer press material where
// available (see `sources`); paint swatch hex values are on-screen approximations.

export const CARS = [
  {
    id: 'porsche-911',
    brand: 'Porsche',
    model: '911 Carrera 4S',
    short: '911',
    generation: 'Type 991.1',
    years: '2012 – 2015',
    lede: 'The all-wheel-drive 911 of the 991 generation, with a 3.8-litre flat-six and the wider body shared with the Carrera 4.',
    lengthM: 4.49,
    model3d: {
      url: new URL('./assets/porsche-911.glb', import.meta.url),
      paint: ['paint'],
      lights: { front: ['lights'] },
      wheels: ['Cylinder.000', 'Cylinder.001'],
      ground: 'Material',
      credit: { title: '(FREE) Porsche 911 Carrera 4S', author: 'Lionsharp Studios', url: 'https://sketchfab.com/3d-models/free-porsche-911-carrera-4s-d01b254483794de3819786d93e0e1ebf', license: 'CC BY-SA 4.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/' },
    },
    specs: [
      ['Engine', '3.8 L flat-six, naturally aspirated'],
      ['Power', '400 PS (294 kW) at 7,400 rpm'],
      ['Torque', '440 Nm at 5,600 rpm'],
      ['0–100 km/h', '4.5 s manual · 4.1 s PDK with Sport Chrono'],
      ['Top speed', '299 km/h'],
      ['Drive', 'All-wheel drive'],
      ['Kerb weight', '1,445 kg (manual)'],
    ],
    story: [
      'Porsche added the Carrera 4 and 4S to the 991 range at the Paris Motor Show in September 2012, a year after the rear-drive cars debuted in Frankfurt.',
      'The 991 grew its wheelbase by 100 mm to 2,450 mm over the 997, and its body mixes high-strength steel, aluminium and composites to keep weight down.',
    ],
    details: [
      'The 4S carries the wider rear body of the all-wheel-drive cars.',
      'Seven-speed manual or seven-speed PDK dual-clutch gearbox.',
      'The engine still hangs behind the rear axle, as in every 911 since 1963.',
    ],
    paints: [
      { name: 'Guards Red', code: '80K', hex: '#b8121b', finish: 'solid' },
      { name: 'Racing Yellow', code: '1S1', hex: '#f2c200', finish: 'solid' },
      { name: 'GT Silver Metallic', code: 'M7Z', hex: '#a2a5a8', finish: 'metallic' },
      { name: 'Agate Grey Metallic', code: 'M7S', hex: '#6c6d70', finish: 'metallic' },
      { name: 'Sapphire Blue Metallic', code: 'M5J', hex: '#1c2b4c', finish: 'metallic' },
      { name: 'Aqua Blue Metallic', code: 'M5R', hex: '#2b6f93', finish: 'metallic' },
      { name: 'Basalt Black Metallic', code: 'C9Z', hex: '#1b1c20', finish: 'metallic' },
      { name: 'Black', code: '041', hex: '#0b0b0c', finish: 'solid' },
    ],
    sources: [
      ['Wikipedia: Porsche 911 (991)', 'https://en.wikipedia.org/wiki/Porsche_911_(991)'],
      ['Porsche paint codes, 2013 911', 'https://www.automotivetouchup.com/touch-up-paint/porsche/2013/911/'],
    ],
  },

  {
    id: 'mercedes-sl63',
    brand: 'Mercedes-AMG',
    model: 'SL 63',
    short: 'SL 63',
    generation: 'R232',
    years: '2022 – today',
    lede: 'The first SL developed entirely by AMG: a 2+2 roadster with a fabric roof, all-wheel drive and a 4.0-litre biturbo V8.',
    lengthM: 4.71,
    model3d: {
      url: new URL('./assets/mercedes-sl63.glb', import.meta.url),
      paint: ['SL63_paint'],
      lights: {
        front: ['SL63_lowbeams-F.001', 'SL63_runninglight-Fr', 'SL63_runninglight-Fl'],
        rear: ['SL63_brakelight', 'SL63_runninglight-R'],
      },
      wheels: ['SL63_wheel', 'SL63_wheel.001', 'SL63_wheel.002', 'SL63_wheel.003'],
      credit: { title: 'Mersedes-Benz SL63 AMG [Free]', author: 'Black Snow', url: 'https://sketchfab.com/3d-models/mersedes-benz-sl63-amg-free-f7a625e6f5de425e89e84ae2e92cad65', license: 'CC BY 4.0', licenseUrl: 'https://creativecommons.org/licenses/by/4.0/' },
    },
    specs: [
      ['Engine', '4.0 L V8 biturbo (M177)'],
      ['Power', '585 PS (430 kW)'],
      ['Torque', '800 Nm'],
      ['0–100 km/h', '3.6 s'],
      ['Top speed', '315 km/h'],
      ['Gearbox', 'AMG SPEEDSHIFT MCT 9G'],
      ['Drive', 'All-wheel drive (4MATIC+)'],
    ],
    story: [
      'The seventh-generation SL was introduced on 28 October 2021. It is the first SL developed by Mercedes-AMG and sold only under the AMG name.',
      'It sits on an aluminium space frame and is built in Bremen. Production began in March 2022.',
    ],
    details: [
      'The first SL with all-wheel drive.',
      'The fabric roof is back, saving 21 kg over the previous folding metal roof and using electric motors in place of hydraulics.',
      'Seating for 2+2 is standard.',
      'Rear-axle steering is standard.',
    ],
    paints: [
      { name: 'MANUFAKTUR Hyper Blue', code: 'metallic', hex: '#1552c4', finish: 'metallic' },
      { name: 'MANUFAKTUR Patagonia Red', code: 'metallic', hex: '#7a0d17', finish: 'metallic' },
      { name: 'MANUFAKTUR Monza Grey', code: 'magno (matte)', hex: '#6a6c6c', finish: 'matte' },
      { name: 'MANUFAKTUR Moonlight White', code: 'magno (matte)', hex: '#e6e4de', finish: 'matte' },
      { name: 'Starling Blue', code: 'metallic', hex: '#22405f', finish: 'metallic' },
      { name: 'Selenite Grey', code: 'metallic', hex: '#5b5e62', finish: 'metallic' },
      { name: 'Sun Yellow', code: 'solid', hex: '#f3c10e', finish: 'solid' },
      { name: 'Obsidian Black', code: 'metallic', hex: '#131417', finish: 'metallic' },
    ],
    paintNote: 'A selection from the 2025 Mercedes-AMG SL colour list. Magno finishes are matte.',
    sources: [
      ['Wikipedia: Mercedes-Benz SL (R232)', 'https://en.wikipedia.org/wiki/Mercedes-Benz_SL_(R232)'],
      ['Mercedes-Benz of South Bay: 2025 SL colours', 'https://www.sbmercedes.com/research/mercedes-amg-sl-roadster-colors.htm'],
    ],
  },
];
